services:

  frontend:
      build: ./frontend
      volumes:
        - ./frontend:/app
        - /app/node_modules
      ports:
        - "5173:5173"
      environment:
        - VITE_API_URL=http://localhost:8000
      networks:
        - memtech-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: memtech-backend
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
      - ./backend/staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_URL=postgres://memtech:memtech@db:5432/memtech
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-admin@memtech.fr}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-admin}
    depends_on:
      - db
      - onlyoffice
    networks:
      - memtech-network

  db:
    image: postgres:15
    container_name: memtech-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=memtech
      - POSTGRES_USER=memtech
      - POSTGRES_PASSWORD=memtech
    ports:
      - "5432:5432"
    networks:
      - memtech-network

  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    environment:
      - JWT_ENABLED=false
      - JWT_SECRET=MaSuperCleJWTUltraSecrete2025!
      - WOPI_ENABLED=true
      - ALLOW_CORS=true
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,https://localhost:5173,http://127.0.0.1:5173,https://127.0.0.1:5173,http://localhost:8000,https://localhost:8443,http://127.0.0.1:8000,https://127.0.0.1:8443
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
      - onlyoffice_logs:/var/log/onlyoffice
    networks:
      - memtech-network

networks:
  memtech-network:
    driver: bridge

volumes:
  postgres_data:
  onlyoffice_data:
  onlyoffice_logs: 