version: '3.8'

services:
  onlyoffice:
    image: onlyoffice/documentserver:8.2
    container_name: onlyoffice
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=MaSuperCleJWTUltraSecrete2025!
      - WOPI_ENABLED=true
      - ALLOW_CORS=true
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,https://localhost:5173,http://127.0.0.1:5173,https://127.0.0.1:5173,http://localhost:8000,https://localhost:8443,http://127.0.0.1:8000,https://127.0.0.1:8443
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
      - onlyoffice_logs:/var/log/onlyoffice
    networks:
      - memtech-network

networks:
  memtech-network:
    driver: bridge

volumes:
  onlyoffice_data:
  onlyoffice_logs: 