# Generated by Django 5.0.3 on 2025-04-19 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MEMO_TECHNIQUE', 'Mémoire technique'), ('SOGED', 'SOGED'), ('SOPAQ', 'SOPAQ'), ('SOPRE', 'SOPRE'), ('PPSPS', 'PPSPS'), ('PAQ', 'PAQ')], max_length=20, unique=True, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Obligatoire')),
            ],
            options={
                'verbose_name': 'type de document',
                'verbose_name_plural': 'types de documents',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('offer_delivery_date', models.DateField(null=True, verbose_name="Date de remise de l'offre")),
                ('maitre_ouvrage', models.CharField(max_length=200, null=True, verbose_name="Maître d'ouvrage")),
                ('maitre_oeuvre', models.CharField(max_length=200, null=True, verbose_name="Maître d'œuvre")),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Non commencé'), ('IN_PROGRESS', 'En cours de rédaction'), ('UNDER_REVIEW', 'En relecture'), ('IN_CORRECTION', 'En correction'), ('APPROVED', 'Validé')], default='NOT_STARTED', max_length=20, verbose_name='Statut')),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authored_documents', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.documenttype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_documents', to='projects.project')),
                ('reviewers', models.ManyToManyField(blank=True, related_name='documents_to_review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document du projet',
                'verbose_name_plural': 'documents du projet',
                'unique_together': {('project', 'document_type')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='required_documents',
            field=models.ManyToManyField(through='projects.ProjectDocument', to='projects.documenttype', verbose_name='Documents requis'),
        ),
        migrations.CreateModel(
            name='TechnicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('UNDER_REVIEW', 'En révision'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_reports', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_reports', to='projects.project', verbose_name='Projet')),
                ('reviewers', models.ManyToManyField(related_name='reports_to_review', to=settings.AUTH_USER_MODEL, verbose_name='Réviseurs')),
            ],
            options={
                'verbose_name': 'rapport technique',
                'verbose_name_plural': 'rapports techniques',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RC', 'Règlement de Consultation'), ('CCTP', 'Cahier des Clauses Techniques Particulières')], max_length=10, verbose_name='Type')),
                ('file', models.FileField(upload_to='reference_documents/', verbose_name='Fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_documents', to='projects.project')),
            ],
            options={
                'verbose_name': 'document de référence',
                'verbose_name_plural': 'documents de référence',
                'unique_together': {('project', 'type')},
            },
        ),
    ]
