# Generated by Django 4.2.9 on 2025-04-13 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalreport',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_reports', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='technicalreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_reports', to='projects.project', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='technicalreport',
            name='reviewers',
            field=models.ManyToManyField(related_name='reports_to_review', to=settings.AUTH_USER_MODEL, verbose_name='Réviseurs'),
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Chef de projet'),
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name="Membres de l'équipe"),
        ),
    ]
