# Generated by Django 5.0.3 on 2025-04-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team_members',
        ),
        migrations.AddField(
            model_name='project',
            name='maitre_oeuvre',
            field=models.CharField(max_length=200, null=True, verbose_name="Maître d'œuvre"),
        ),
        migrations.AddField(
            model_name='project',
            name='maitre_ouvrage',
            field=models.CharField(max_length=200, null=True, verbose_name="Maître d'ouvrage"),
        ),
        migrations.AddField(
            model_name='project',
            name='offer_delivery_date',
            field=models.DateField(null=True, verbose_name="Date de remise de l'offre"),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20, verbose_name='Statut'),
        ),
    ]
