# Generated by Django 5.0.3 on 2025-04-20 15:58

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_referencedocument_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencedocument',
            name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='referencedocument',
            name='file',
            field=models.FileField(upload_to=projects.models.reference_document_path, verbose_name='Fichier'),
        ),
    ]
