# Generated by Django 5.0.3 on 2025-04-21 06:02

import django.db.models.deletion
from django.db import migrations, models

def forward_func(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    MOA = apps.get_model('moas', 'MOA')
    MOE = apps.get_model('moas', 'MOE')
    
    # Créer les MOA et MOE pour les projets existants
    for project in Project.objects.all():
        if project.maitre_ouvrage_old:
            moa, _ = MOA.objects.get_or_create(
                name=project.maitre_ouvrage_old,
                defaults={
                    'address': 'À renseigner',
                }
            )
            project.maitre_ouvrage = moa
        
        if project.maitre_oeuvre_old:
            moe, _ = MOE.objects.get_or_create(
                name=project.maitre_oeuvre_old,
                defaults={
                    'address': 'À renseigner',
                }
            )
            project.maitre_oeuvre = moe
        
        project.save()

def reverse_func(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    
    for project in Project.objects.all():
        if project.maitre_ouvrage:
            project.maitre_ouvrage_old = project.maitre_ouvrage.name
        if project.maitre_oeuvre:
            project.maitre_oeuvre_old = project.maitre_oeuvre.name
        project.save()

class Migration(migrations.Migration):

    dependencies = [
        ('moas', '0001_initial'),
        ('projects', '0004_remove_referencedocument_uploaded_by_and_more'),
    ]

    operations = [
        # Étape 1 : Renommer les anciens champs
        migrations.RenameField(
            model_name='project',
            old_name='maitre_ouvrage',
            new_name='maitre_ouvrage_old',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='maitre_oeuvre',
            new_name='maitre_oeuvre_old',
        ),
        
        # Étape 2 : Créer les nouveaux champs ForeignKey
        migrations.AddField(
            model_name='project',
            name='maitre_ouvrage',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='projects_as_moa',
                to='moas.moa',
                verbose_name='Maître d\'ouvrage'
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='maitre_oeuvre',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='projects_as_moe',
                to='moas.moe',
                verbose_name='Maître d\'œuvre'
            ),
        ),
        
        # Étape 3 : Migration des données
        migrations.RunPython(forward_func, reverse_func),
        
        # Étape 4 : Supprimer les anciens champs
        migrations.RemoveField(
            model_name='project',
            name='maitre_ouvrage_old',
        ),
        migrations.RemoveField(
            model_name='project',
            name='maitre_oeuvre_old',
        ),
    ]
