# Generated by Django 5.0.3 on 2025-04-28 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_maitre_oeuvre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdocument',
            name='author',
        ),
        migrations.RemoveField(
            model_name='projectdocument',
            name='reviewers',
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='comments',
            field=models.JSONField(blank=True, default=list, verbose_name='Commentaires'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='completion_percentage',
            field=models.FloatField(default=0, verbose_name='Pourcentage de complétion'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière notification'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='needs_correction',
            field=models.BooleanField(default=False, verbose_name='Nécessite des corrections'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='review_cycle',
            field=models.IntegerField(default=1, verbose_name='Cycle de relecture'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents_to_review', to=settings.AUTH_USER_MODEL, verbose_name='Relecteur'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='status_history',
            field=models.JSONField(blank=True, default=list, verbose_name='Historique des statuts'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents_to_write', to=settings.AUTH_USER_MODEL, verbose_name='Rédacteur'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'En rédaction'), ('REVIEW_1', 'Première relecture'), ('CORRECTION', 'En correction'), ('REVIEW_2', 'Deuxième relecture'), ('VALIDATION', 'En validation finale'), ('APPROVED', 'Validé')], default='DRAFT', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('review_cycle', models.IntegerField(default=1, verbose_name='Cycle de relecture')),
                ('requires_correction', models.BooleanField(default=False, verbose_name='Nécessite des corrections')),
                ('resolved', models.BooleanField(default=False, verbose_name='Résolu')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_comments', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_comments', to='projects.projectdocument', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'commentaire de document',
                'verbose_name_plural': 'commentaires de document',
                'ordering': ['-created_at'],
            },
        ),
    ]
