# Generated by Django 5.0.3 on 2025-04-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='moas/logos/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': "Maître d'ouvrage",
                'verbose_name_plural': "Maîtres d'ouvrage",
                'db_table': 'moas_moa',
            },
        ),
    ]
