# Generated by Django 5.0.3 on 2025-04-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('logo', models.BinaryField(blank=True, null=True, verbose_name='Logo')),
            ],
            options={
                'verbose_name': "Maître d'œuvre",
                'verbose_name_plural': "Maîtres d'œuvre",
                'db_table': 'moe',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='moa',
            options={'managed': False, 'verbose_name': "Maître d'ouvrage", 'verbose_name_plural': "Maîtres d'ouvrage"},
        ),
    ]
