# Generated by Django 5.0.3 on 2025-04-21 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_alter_project_maitre_oeuvre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du document')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('administrative', 'Document administratif'), ('technical', 'Document technique'), ('financial', 'Document financier'), ('other', 'Autre')], default='other', max_length=50, verbose_name='Catégorie')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de validation'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='draft', max_length=50, verbose_name='Statut')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project', verbose_name='Projet associé')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur ayant uploadé')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-upload_date'],
            },
        ),
    ]
