# Generated by Django 5.0.3 on 2025-04-16 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'template',
                'verbose_name_plural': 'templates',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='ContenuReutilisable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
                ('theme', models.CharField(max_length=50, verbose_name='Thème')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contenus', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'contenu réutilisable',
                'verbose_name_plural': 'contenus réutilisables',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('statut', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('version', models.CharField(max_length=50, verbose_name='Version')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projets', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('ordre', models.IntegerField(verbose_name='Ordre')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_sections', to='core.section', verbose_name='Section parente')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
                'ordering': ['projet', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='GenerationIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='Prompt')),
                ('contenu_genere', models.TextField(verbose_name='Contenu généré')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generations', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='core.projet', verbose_name='Projet')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='core.section', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'génération IA',
                'verbose_name_plural': 'générations IA',
                'ordering': ['-date_generation'],
            },
        ),
    ]
