# Generated by Django 5.0.3 on 2025-04-29 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0006_remove_projectdocument_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_data', models.JSONField()),
                ('summary_data', models.JSONField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rc_analyses', to='projects.project')),
            ],
            options={
                'verbose_name': 'analyse de RC',
                'verbose_name_plural': 'analyses de RC',
                'ordering': ['-created_at'],
            },
        ),
    ]
