# Generated by Django 5.0.3 on 2025-05-06 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom du tag')),
            ],
        ),
        migrations.CreateModel(
            name='BibliothequeMemoireTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(default='Mémoire Technique', max_length=50, verbose_name='Type de document')),
                ('categorie', models.CharField(choices=[('texte', 'Texte'), ('tableau', 'Tableau'), ('photo', 'Photo'), ('document_technique', 'Document technique'), ('signalisation', 'Signalisation'), ('procedure', 'Procédure'), ('fiche_technique', 'Fiche technique')], max_length=50, verbose_name='Catégorie')),
                ('sous_categorie', models.CharField(blank=True, choices=[('chantier', 'Photos de chantier'), ('equipement', 'Équipements'), ('installation', 'Installations'), ('documentation', 'Documentation')], max_length=50, null=True, verbose_name='Sous-catégorie')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('droits_acces', models.CharField(default='admin,editeur', max_length=200, verbose_name="Droits d'accès")),
                ('recent', models.DateTimeField(blank=True, null=True, verbose_name='Dernier accès')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elements_bibliotheque_mt', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('favoris', models.ManyToManyField(blank=True, related_name='favoris_bibliotheque_mt', to=settings.AUTH_USER_MODEL, verbose_name='Favoris')),
            ],
            options={
                'verbose_name': 'élément de bibliothèque Mémoire Technique',
                'verbose_name_plural': 'éléments de bibliothèque Mémoire Technique',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='BibliothequeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('mime_type', models.CharField(max_length=50, verbose_name='Type MIME')),
                ('image_blob', models.BinaryField(verbose_name='Image (BLOB)')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bibliotheque_mt.bibliothequememoiretechnique', verbose_name='Élément de bibliothèque associé')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(verbose_name='Texte du commentaire')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
        ),
        migrations.AddField(
            model_name='bibliothequememoiretechnique',
            name='commentaires',
            field=models.ManyToManyField(blank=True, related_name='element_bibliotheque_mt', to='bibliotheque_mt.commentaire', verbose_name='Commentaires'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.PositiveSmallIntegerField(verbose_name='Valeur de la note')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
        ),
        migrations.AddField(
            model_name='bibliothequememoiretechnique',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='element_bibliotheque_mt', to='bibliotheque_mt.note', verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='bibliothequememoiretechnique',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='elements_bibliotheque_mt', to='bibliotheque_mt.tag', verbose_name='Tags'),
        ),
    ]
