# Migration corrigée : n'ajoute que le champ 'sous_categorie' à BibliothequeImage.
# L'ajout du champ 'contenu' à BibliothequeMemoireTechnique a été supprimé car il existe déjà.
# Generated by Django 5.0.3 on 2025-05-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque_mt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliothequeimage',
            name='sous_categorie',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sous-catégorie'),
        ),
    ]
