# Generated by Django 5.0.3 on 2025-05-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque_mt', '0003_update_sous_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliothequememoiretechnique',
            name='contenu',
            field=models.TextField(blank=True, null=True, verbose_name='Contenu'),
        ),
    ]
